---
ID: "78b353d5-fb08-4967-b2fb-3d7c5f80212b"
Parent: "167a8a05-2f6d-49e5-80af-47abbccd52ab"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/Sitecore + Microsoft Teams Integration/Functions/Composition/Compose-LighthouseResults"
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Compose-LighthouseResults {
        [CmdletBinding()]
        param(
            [string]$PerformanceScore,
            [string]$SeoScore,
            [string]$AccessibilityScore,
            [string]$BestPracticesScore
        )
        
        Import-Function Get-Template
        $lighthouseScoreSchema = Get-Template "Lighthouse Score"
        
        $lighthouseScoreSection = getProgressCircle "Performance" $PerformanceScore;
        $lighthouseScoreSection += getProgressCircle "SEO" $SeoScore;
        $lighthouseScoreSection += getProgressCircle "Accessibility" $AccessibilityScore;
        $lighthouseScoreSection += getProgressCircle "Best Practices" $BestPracticesScore;
        return $lighthouseScoreSection
    }
    
    function getProgressCircle($category, $score){
        return $lighthouseScoreSchema -replace "{category}", $category `
                -replace "{score}", $score `
                -replace "{position}", ((10 - [math]::Truncate($score/10)) * 10)
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210809T124123Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "976e89bf-79b0-42d9-891a-3228794bbf84"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210810T112941Z
