---
ID: "2904d218-722f-4103-b45f-45e3f8067c54"
Parent: "2da9e563-d99f-49ca-8e7b-b067c73c1d3f"
Template: "dd22f1b3-bd87-4db2-9e7d-f7a496888d43"
Path: "/sitecore/system/Modules/PowerShell/Script Library/Sitecore + Microsoft Teams Integration/Functions/Setup/Configure-Webhook"
SharedFields:
- ID: "b1a94ff0-6897-47c0-9c51-aa6acb80b1f0"
  Hint: Script
  Value: |
    function Configure-Webhook{    
        [CmdletBinding()]
        param(
        	[ID]$WebhookID
        )
    
        Import-Function Create-NotificationAction 
        Import-Function Delete-NotificationAction
        Import-Function Send-UpdateNotification
        Import-Function Get-HostUrl
    
        $selectedWebhookItem = $null;
        $isCreateRequest = $WebhookID -eq $null
        
        if(-Not $isCreateRequest){
            $selectedWebhookItem = Get-Item -Path master: -ID $WebhookID
            $name = $webhookName = $selectedWebhookItem.NickName
            $endpoint = $selectedWebhookItem.WebhookEndpoint
        	$publishNotificationSettings = $selectedWebhookItem.PublishNotificationSettings
        }
        
        $testEndpointSchemaItem = Get-Item -Path master: -ID "{3BA84DF9-3DF7-40BD-8982-9619CB3529D3}"
        $generalTab = @(
    		@{ Tab="GENERAL"; Name="name"; Title="Name"; Placeholder="Enter a Nick Name for this Endpoint Configuration"; Mandatory=$true; Columns=10; ParentGroupId=1; HideOnValue="0"; },
    		@{ Tab="GENERAL"; Name="endpointTitle"; Title="Teams Endpoint URL"; Editor="info"; ParentGroupId=1; HideOnValue="0"; },
    		@{ Tab="GENERAL"; Name="webhookName"; Title=""; ParentGroupId=1; HideOnValue="1"; },
    		@{ Tab="GENERAL"; Name="endpoint"; Title=""; Placeholder="Enter Teams Endpoint URL"; Mandatory=$true; lines=2; Columns=10; ParentGroupId=1; HideOnValue="0"; },
    		@{ Tab="GENERAL"; Name="testEndpoint"; Title=""; Options=[ordered]@{"Test"= "" }; Editor="link"; Columns=2; ParentGroupId=1; HideOnValue="0"; },
    		@{ Tab="GENERAL"; Name="testEndpointSchema"; Title=""; Value=$testEndpointSchemaItem.MessageSchema; Editor="info"; ParentGroupId=1; HideOnValue="0"; }
    	)
    
    	$workflowTab = @(
    		@{ Tab="WORKFLOW"; Name="workflows"; Title=""; Value="Select the workflow actions to receive status change notifications";  Editor="info"; ParentGroupId=1; HideOnValue="0"; }
    	)
    
    	$workflowItems = Get-ChildItem -Path "master:\sitecore\system\Workflows"
    
    	$workflowStateIndex = 0;
    	$workflowItems | ForEach-Object { 
    		$workflowName = $_.DisplayName;
    		$workflowTab += @{ Tab="WORKFLOW"; Name=$workflowName; Value=""; Title=$workflowName; Editor="info"; ParentGroupId=2; HideOnValue="0"; }
    		Get-ChildItem -Path "master:$($_.Paths.FullPath)" | Where-Object {$_.TemplateName -eq "State"} | ForEach-Object { 
    			$workflowStateName = $_.Name;
    			$options = [ordered]@{};
    			$selectedOptions = @();
    			Get-ChildItem -Path "master:$($_.Paths.FullPath)" | Where-Object {$_.TemplateName -eq "Command"} | ForEach-Object { 
    				$options[$_.Name] = $_.ID.ToString();
    				if(-Not $isCreateRequest){
    					if(Test-Path -Path "master:$($_.ItemPath)/Send-TeamsNotification-$($WebhookID.ToShortID())"){
    						$selectedOptions += $_.ID.ToString();
    					}
    				}
    			}
    			if($options.Count -gt 0){
    				if(-Not $isCreateRequest){
    					Set-Variable "workflowCommands$($workflowStateIndex)" -Value $selectedOptions
    				}
    				$workflowTab += @{ Tab="WORKFLOW"; Name="workflowState$($workflowStateIndex)"; Value=$workflowStateName; Title="";Editor="info"; ParentGroupId=2; HideOnValue="0"; }
    				$workflowTab += @{ Tab="WORKFLOW"; Name="workflowCommands$($workflowStateIndex)"; Title=""; Options=$options; Editor="checklist"; ParentGroupId=2; HideOnValue="0"; }
    				$workflowStateIndex++;
    			}
    		}
    	}
    
    	$publishTab=@(
    		@{ Tab="PUBLISH"; Name="publishInfo"; Title=""; Value="List all the content locations to receive change notifications for published items and links"; Editor="info"; ParentGroupId=1; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishLocationTitle"; Title="Content Path"; Editor="info"; Columns=5; ParentGroupId=2; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishLanguageTitle"; Title="Content Language"; Editor="info"; Columns=2; ParentGroupId=2; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishTargetTitle"; Title="Publishing Target"; Editor="info"; Columns=2; ParentGroupId=2; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishSubitemsTitle"; Title="Include Subitems"; Editor="info"; Columns=2; ParentGroupId=2; HideOnValue="0"; }
    	)
    	$publishTab += @(
    		@{ Tab="PUBLISH"; Name="publishLocation"; Title=""; Value=""; Tooltip=""; Editor="info"; Columns=5; ParentGroupId=3; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishLanguage"; Title=""; Value=""; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=3; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishTarget"; Title=""; Value=""; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=3; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishSubitems"; Title=""; Value=""; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=3; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishDeleteOption"; Title=""; Options=[ordered]@{"Delete"=""}; Editor="link"; Columns=1; ParentGroupId=3; HideOnValue="0"; }
    	)
    	
    	if(-Not $isCreateRequest){
            if($selectedWebhookItem.PublishNotificationSettings.Length -gt 0){
                $publishNotificationEntries = $selectedWebhookItem.PublishNotificationSettings.Split('&');
                for ($i=0; $i -lt $publishNotificationEntries.Length; $i++){
                    $contentLocation = [System.Web.HttpUtility]::UrlDecode($publishNotificationEntries[$i].Split('=')[0]);
                    $contentOptions = ([System.Web.HttpUtility]::UrlDecode($publishNotificationEntries[$i].Split('=')[1])).Split('|');
                    $publishTab += @(
                		@{ Tab="PUBLISH"; Name="publishLocation$($i)"; Title=""; Value=$contentLocation; Tooltip=""; Editor="info"; Columns=5; ParentGroupId=4; HideOnValue="0"; },
                		@{ Tab="PUBLISH"; Name="publishLanguage$($i)"; Title=""; Value=$contentOptions[0]; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=4; HideOnValue="0"; },
                		@{ Tab="PUBLISH"; Name="publishTarget$($i)"; Title=""; Value=$contentOptions[1]; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=4; HideOnValue="0"; },
                		@{ Tab="PUBLISH"; Name="publishSubitems$($i)"; Title=""; Value=$contentOptions[2]; Tooltip=""; Editor="info"; Columns=2; ParentGroupId=4; HideOnValue="0"; },
                		@{ Tab="PUBLISH"; Name="publishDeleteOption$($i)"; Title=""; Options=[ordered]@{"Delete"=""}; Editor="link"; Columns=1; ParentGroupId=4; HideOnValue="0"; }
                	)
                }
            }
    	}
    	
    	$publishTab += @(
    		@{ Tab="PUBLISH"; Name="publishLocationSelector"; Title=""; Source="/sitecore/content/"; Editor="droptree"; Columns=5; ParentGroupId=5; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishLanguageSelector"; Title=""; Source="DataSource=/sitecore/system/Languages&DatabaseName=master"; Editor="droplist"; Columns=2; ParentGroupId=5; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishTargetSelector"; Title=""; Source="DataSource=/sitecore/system/Publishing targets&DatabaseName=master"; Editor="droplist"; Columns=2; ParentGroupId=5; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishSubitemsSelector"; Title=""; Editor="checkbox"; Value=$true; Columns=2; ParentGroupId=5; HideOnValue="0"; },
    		@{ Tab="PUBLISH"; Name="publishAddOption"; Title=""; Options=[ordered]@{"Add"=""}; Editor="link"; Columns=1; ParentGroupId=5; HideOnValue="0"; }
    		@{ Tab="PUBLISH"; Name="publishNotificationSettings"; Title=""; ParentGroupId=6; HideOnValue="1"; }
    	)
    
        $allTabs = $generalTab + $workflowTab + $publishTab
        
        $okButtonName = @("Update", "Create")[$isCreateRequest]
        $dialogProps = @{
        	Title = "Configure Teams Endpoint"
        	Description = "Configure all the notification settings for a new or existing Teams Endpoint"
        	Width = 500 
        	Height = 600
        	OkButtonName = $okButtonName
        	CancelButtonName = "Cancel"
        	ShowHints = $true
        	Icon = "office/16x16/graph_triangle.png"
        	Parameters = $allTabs
        }
        
        $result = Read-Variable @dialogProps -Validator {
            $webhooksItem = Get-Item -Path "master:" -ID "{AAEB319C-3BC9-411F-B0B9-721B5826AD0F}"
            $existingWebhooks = $webhooksItem.Children | Get-ItemField -ReturnType Field -Name "NickName" | Select-Object -Expand Value
            $newWebhookName = $variables.name.Value
            if (($existingWebhooks -contains $newWebhookName) -and ($newWebhookName -ne $variables.webhookName.Value))
            {
                $variables.name.Error = "Name already taken. Please enter a different name."
            }
        }
        
        if($result -eq "ok") {
            if($isCreateRequest){
                $webhooksItem = Get-Item -Path "master:" -ID "{AAEB319C-3BC9-411F-B0B9-721B5826AD0F}"
            	$webhookTemplate = Get-Item -Path "master:" -ID "{7AA3E7B4-B8D4-4972-9B94-A82604E977F7}"
            	$webhookItemName = [Sitecore.Data.Items.ItemUtil]::ProposeValidItemName($name) 
                $webhookItemPath = "master:$($webhooksItem.ItemPath)\$($webhookItemName)"
                if(Test-Path -Path $webhookItemPath){
                    $webhookItemPath += Get-Random
                }
            	$selectedWebhookItem = New-Item -ItemType $webhookTemplate.ItemPath -Path $webhookItemPath
            	
                Get-ChildItem -Path "master:$($selectedWebhookItem.ItemPath)/Scripts" | Foreach-Object {
                    $updatedScript = $_.Script -replace "{webhookid}", $selectedWebhookItem.ID
                    Set-ItemProperty -Path "master:$($_.ItemPath)" -Name "Script" -Value $updatedScript
                }
            }
            $selectedWebhookItem.Editing.BeginEdit()
        	$selectedWebhookItem.NickName = $name
        	$selectedWebhookItem.WebhookEndpoint = $endpoint
        	$selectedWebhookItem.PublishNotificationSettings = $publishNotificationSettings
        	$selectedWebhookItem.Editing.EndEdit()
            
            $selectedWorkflowCommands=@();
        	for($i = 0; Test-Path "variable:workflowCommands$($i)"; $i++){
        	    $workflowCommandItemIDs = Get-Variable "workflowCommands$($i)" -Value
        	    $selectedWorkflowCommands += $workflowCommandItemIDs
        	}
        	
            $workflowCommandItems = Get-Item -Path master: -Query "/sitecore/system/Workflows//*[@@templatename='Command']" 
        
            foreach($workflowCommandItem in $workflowCommandItems){
                if($selectedWorkflowCommands -contains $workflowCommandItem.ID.ToString()){
        	        Create-NotificationAction -WorkflowCommandItemID $workflowCommandItem.ID -WebhookItem $selectedWebhookItem
                }
        	    else{
        	        Delete-NotificationAction -WorkflowCommandItemID $workflowCommandItem.ID -WebhookItem $selectedWebhookItem
        	    }
            }
            Send-UpdateNotification -Endpoint $endpoint -Message $notificationMessage -IsNewEndpoint $isCreateRequest
            
            Invoke-Javascript "window.top.location.reload()"
        }
        else{
            Close-Window
        }
    }
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20210523T023353Z
    - ID: "52807595-0f8f-4b20-8d2a-cb71d28c6103"
      Hint: __Owner
      Value: |
        sitecore\Admin
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\Admin
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "f608a147-9587-4bac-99a6-ad1525432c3e"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\Admin
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20210601T190722Z
